# Generated by Django 4.2.1 on 2023-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordemservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(),
        ),
    ]
